# This is a basic workflow to help you get started with Actions
name: CI

# Controls when the action will run. 
on: [push, pull_request]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Install Java
      - name: Setup Java JDK
        uses: actions/setup-java@v2.0.0
        with: 
          java-version: 8
          distribution: 'adopt'

      # Build and run the application
      - name: Build and run the application
        run: |
            cd src/org/triamici
            javac *.java
            cd ../..
            java TriAmici.TriAmici
        timeout-minutes: 1
